apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx
spec:
   replicas: 1
   selector:
    matchLabels: 
     name: nginx
   template:
     metadata:
       name: test-pod
       labels:
         name: nginx
     spec:
      containers:
        - image: nginx    # cloudzenix/harness
          name: nginx
          ports:
           - containerPort: 80
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx
  name: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: nginx
