apiVersion: apps/v1
kind: Deployment
metadata:
   name: javawebapp
spec:
   replicas: 1
   selector:
    matchLabels:
     name: javawebapp
   template:
     metadata:
       name: test-pod
       labels:
         name: javawebapp
     spec:
      containers:
        - image: cloudzenix/harness
          name: javawebapp
          ports:
           - containerPort: 80
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: javawebapp
  name: javawebapp
spec:
  type: NodePort
  ports:
    - port: 30001
      targetPort: 30001
  selector:
    name: javawebapp
